/**
 * Tray Icon Loader — loads pre-generated TrackFlow branded tray icons.
 *
 * macOS: Template images (monochrome clock-arc logo with colored status dot).
 *        The OS auto-adapts the monochrome part for light/dark menu bars.
 * Windows/Linux: Full-color icons — green circle = tracking, gray circle = idle.
 *        Both show the clock-arc logo silhouette.
 *
 * Icons are generated by scripts/generate-brand-icons.js and stored in build/tray/.
 * They're bundled via extraResources so they're available in both dev and packaged builds.
 */
const { nativeImage, app } = require('electron');
const path = require('path');
const fs = require('fs');

// ── Icon file resolution ────────────────────────────────────────────────────
// In dev: build/tray/ relative to project root
// In packaged: Resources/tray/ (via extraResources)
function getTrayDir() {
  const candidates = [
    path.join(process.resourcesPath, 'tray'),              // Packaged (extraResources)
    path.join(__dirname, '..', '..', 'build', 'tray'),     // Dev (src/main -> desktop/build)
  ];
  for (const dir of candidates) {
    if (fs.existsSync(dir)) return dir;
  }
  return candidates[1]; // Fallback to dev path
}

let _trayDir = null;
function trayDir() {
  if (!_trayDir) _trayDir = getTrayDir();
  return _trayDir;
}

/**
 * Create a macOS template tray icon from the pre-generated PNG.
 * Template images are monochrome; macOS inverts them for dark menu bars.
 * The colored status dot is part of the PNG (not template-controlled).
 */
function createMacIcon(tracking) {
  const filename = tracking ? 'tray-tracking.png' : 'tray-idle.png';
  const iconPath = path.join(trayDir(), filename);

  if (!fs.existsSync(iconPath)) {
    console.warn(`[TrayIcon] Missing: ${iconPath} — using fallback`);
    return createFallbackIcon(tracking);
  }

  const img = nativeImage.createFromPath(iconPath);
  // Mark as @2x (44px = 22pt on retina)
  const resized = img.resize({ width: 22, height: 22 });
  resized.setTemplateImage(true);
  return resized;
}

/**
 * Create a Windows/Linux full-color tray icon from the pre-generated PNG.
 */
function createStandardIcon(tracking) {
  const filename = tracking ? 'tray-tracking-color.png' : 'tray-idle-color.png';
  const iconPath = path.join(trayDir(), filename);

  if (!fs.existsSync(iconPath)) {
    console.warn(`[TrayIcon] Missing: ${iconPath} — using fallback`);
    return createFallbackIcon(tracking);
  }

  return nativeImage.createFromPath(iconPath);
}

/**
 * Fallback: programmatic icon if PNG files are missing.
 * Simple colored circle (no logo detail at this size).
 */
function createFallbackIcon(tracking) {
  const size = process.platform === 'darwin' ? 44 : 32;
  const buf = Buffer.alloc(size * size * 4, 0);
  const color = tracking ? { r: 34, g: 197, b: 94 } : { r: 148, g: 163, b: 184 };
  const cx = size / 2;
  const cy = size / 2;
  const r = size / 2 - 2;

  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const dist = Math.sqrt((x - cx) ** 2 + (y - cy) ** 2);
      if (dist <= r) {
        const idx = (y * size + x) * 4;
        const edge = Math.min(1, Math.max(0, r - dist));
        buf[idx] = color.r;
        buf[idx + 1] = color.g;
        buf[idx + 2] = color.b;
        buf[idx + 3] = Math.round(255 * edge);
      }
    }
  }

  const img = nativeImage.createFromBuffer(buf, { width: size, height: size });
  if (process.platform === 'darwin') img.setTemplateImage(true);
  return img;
}

// ── Icon cache ──────────────────────────────────────────────────────────────
const _cache = new Map();

/**
 * Warm the icon cache. Call once after app.whenReady().
 */
function warmIconCache() {
  getTrayIcon(true);
  getTrayIcon(false);
}

/**
 * Get the appropriate tray icon for the current platform and tracking state.
 * @param {boolean} tracking
 * @returns {Electron.NativeImage}
 */
function getTrayIcon(tracking) {
  const key = `${process.platform}-${tracking}`;
  if (_cache.has(key)) return _cache.get(key);

  const icon = process.platform === 'darwin'
    ? createMacIcon(tracking)
    : createStandardIcon(tracking);
  _cache.set(key, icon);
  return icon;
}

/**
 * Get the notification icon (color logo on transparent background).
 * Used for system notifications to show TrackFlow branding.
 * @returns {Electron.NativeImage|null}
 */
function getNotificationIcon() {
  const iconPath = path.join(trayDir(), 'notification-icon.png');
  if (fs.existsSync(iconPath)) {
    return nativeImage.createFromPath(iconPath);
  }
  return null;
}

module.exports = { getTrayIcon, warmIconCache, getNotificationIcon };
