<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; padding: 20px; }
        h1 { color: #2563eb; font-size: 22px; margin-bottom: 4px; }
        .meta { background: #eff6ff; padding: 12px 15px; border-radius: 8px; margin: 12px 0 18px; font-size: 11px; }
        .meta div { margin: 2px 0; }
        .meta span { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f3f4f6; text-align: left; padding: 7px; border-bottom: 2px solid #e5e7eb; font-size: 10px; }
        td { padding: 7px; border-bottom: 1px solid #e5e7eb; font-size: 10px; }
        tr:nth-child(even) { background-color: #f9fafb; }
        .right { text-align: right; }
        .footer { margin-top: 26px; color: #999; font-size: 10px; border-top: 1px solid #eee; padding-top: 8px; }
    </style>
</head>
<body>
    <h1>TrackFlow — App Usage Report</h1>

    <div class="meta">
        <div>View: <span>{{ $meta['view_label'] }}</span></div>
        <div>Date Range: <span>{{ $meta['date_range'] }}</span></div>
        @if(!empty($meta['resource']))
            <div>Resource: <span>{{ $meta['resource'] }}</span></div>
        @endif
        <div>Exported At: <span>{{ $meta['exported_at'] }}</span></div>
        <div>Exported By: <span>{{ $meta['exported_by'] }}</span></div>
    </div>

    <table>
        <thead>
            <tr>
                @if($view === 'my')
                    <th>Application</th>
                    <th class="right">Duration (h)</th>
                    <th>Productive</th>
                    <th>Window Title</th>
                @elseif($view === 'top')
                    <th>Application</th>
                    <th class="right">Duration (h)</th>
                    <th class="right">Users</th>
                    <th class="right">Days Active</th>
                @else
                    <th>Employee</th>
                    <th>Application</th>
                    <th class="right">Duration (h)</th>
                    <th class="right">Days Used</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    @if($view === 'my')
                        <td>{{ $row->app_name }}</td>
                        <td class="right">{{ number_format(((int) $row->duration_seconds) / 3600, 2) }}</td>
                        <td>{{ $row->is_productive === null ? '—' : ($row->is_productive ? 'Yes' : 'No') }}</td>
                        <td>{{ $row->window_title ?? '—' }}</td>
                    @elseif($view === 'top')
                        <td>{{ $row->app_name }}</td>
                        <td class="right">{{ number_format(((int) $row->duration_seconds) / 3600, 2) }}</td>
                        <td class="right">{{ $row->user_count ?? 0 }}</td>
                        <td class="right">{{ $row->days_active ?? 0 }}</td>
                    @else
                        <td>{{ $row->user_name }}</td>
                        <td>{{ $row->app_name }}</td>
                        <td class="right">{{ number_format(((int) $row->duration_seconds) / 3600, 2) }}</td>
                        <td class="right">{{ $row->days_used ?? 0 }}</td>
                    @endif
                </tr>
            @empty
                <tr><td colspan="4">No app usage matches the selected filters.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by TrackFlow on {{ now()->format('F j, Y \\a\\t g:i A') }}</div>
</body>
</html>
