<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; padding: 20px; }
        h1 { color: #2563eb; font-size: 22px; margin-bottom: 4px; }
        .meta { background: #eff6ff; padding: 12px 15px; border-radius: 8px; margin: 12px 0 18px; font-size: 11px; }
        .meta div { margin: 2px 0; }
        .meta span { font-weight: bold; }
        .summary { margin-bottom: 16px; font-size: 12px; }
        .summary span { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f3f4f6; text-align: left; padding: 7px; border-bottom: 2px solid #e5e7eb; font-size: 10px; }
        td { padding: 7px; border-bottom: 1px solid #e5e7eb; font-size: 10px; }
        tr:nth-child(even) { background-color: #f9fafb; }
        .right { text-align: right; }
        .footer { margin-top: 26px; color: #999; font-size: 10px; border-top: 1px solid #eee; padding-top: 8px; }
    </style>
</head>
<body>
    <h1>TrackFlow — Project Time Report</h1>

    <div class="meta">
        <div>Project(s): <span>{{ $meta['projects'] }}</span></div>
        <div>Resource(s): <span>{{ $meta['resources'] }}</span></div>
        <div>Date Range: <span>{{ $meta['date_range'] }}</span></div>
        <div>View: <span>{{ !empty($group_by_day) ? 'Daily totals per resource and project' : 'Per entry' }}</span></div>
        <div>Exported At: <span>{{ $meta['exported_at'] }}</span></div>
        <div>Exported By: <span>{{ $meta['exported_by'] }}</span></div>
    </div>

    <div class="summary">
        Total: <span>{{ number_format($summary['total_hours'], 2) }}h</span> |
        Billable Amount: <span>${{ number_format($summary['billable_amount'], 2) }}</span> |
        Entries: <span>{{ $summary['entry_count'] }}</span> |
        Resources: <span>{{ $summary['resource_count'] }}</span> |
        Projects: <span>{{ $summary['project_count'] }}</span>
    </div>

    <table>
        <thead>
            <tr>
                <th>Resource</th>
                <th>Project</th>
                <th>Task</th>
                <th>Type</th>
                <th>Date</th>
                <th>Start</th>
                <th>End</th>
                @if(!empty($group_by_day))
                    <th class="right">Entries</th>
                @endif
                <th class="right">Duration (h)</th>
                <th class="right">Activity %</th>
                <th>Billable</th>
                <th class="right">Billable Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    <td>{{ $row['user_name'] }}</td>
                    <td>{{ $row['project_name'] }}</td>
                    <td>{{ $row['task_name'] }}</td>
                    <td>{{ $row['type'] }}</td>
                    <td>{{ $row['date'] }}</td>
                    <td>{{ $row['start_time'] }}</td>
                    <td>{{ $row['end_time'] }}</td>
                    @if(!empty($group_by_day))
                        <td class="right">{{ $row['entry_count'] ?? 1 }}</td>
                    @endif
                    <td class="right">{{ number_format($row['duration_seconds'] / 3600, 2) }}</td>
                    <td class="right">{{ $row['activity_score'] }}%</td>
                    <td>{{ $row['billable'] ? 'Yes' : 'No' }}</td>
                    <td class="right">${{ number_format($row['billable_amount'], 2) }}</td>
                </tr>
            @empty
                <tr><td colspan="11">No time entries match the selected filters.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by TrackFlow on {{ now()->format('F j, Y \\a\\t g:i A') }}</div>
</body>
</html>
